// GENERATED by tools/sync-from-extension.js from ScrapeMASTER/content.js - do not edit by hand.
// Evaluated inside the Google view; resolves to {leads, businessCount, noPhone, signature, hasNext, captcha, url}.
(async () => {
/* ScrapeMASTER - content script (runs on Google search pages)
 *
 * PASSIVE by default: on load it only pings the background. It scrapes ONLY if the
 * background confirms this tab/page belongs to an active job.
 *
 * It reads the page the user's own tab already loaded. It never fetches anything and
 * never opens business websites.
 *
 * Everything here is deliberately written as top-level function declarations / var so a
 * double injection can't throw "already declared". Every scraping assumption is tagged
 * with  // SELECTOR:  or  // ASSUMPTION:  so it is easy to find when Google changes.
 */

// NOTE: INVISIBLE / normalizePhone are duplicated in background.js (no modules in
// content scripts). Keep both copies identical.
var INVISIBLE = /[​-‏‪-‮⁠⁦-⁩﻿]/g;
var LOG = '[ScrapeMASTER]';

function sleep(ms) { return new Promise(function (r) { setTimeout(r, ms); }); }

// -------------------------------------------------------------- phone logic
// Output: optional leading "+" then digits only - NO whitespace of any kind.
function normalizePhone(raw) {
  var s = String(raw == null ? '' : raw).replace(INVISIBLE, '').trim();
  var digits = s.replace(/\D/g, '');            // removes spaces, nbsp, newlines, tabs, dashes, parens
  if (digits.length < 8 || digits.length > 15) return '';
  return (s.charAt(0) === '+' ? '+' : '') + digits;
}

// ASSUMPTION: a phone shown as text is a STANDALONE segment: optional +, 8-15 digits total,
// separated only by spaces/dashes/parens. This rejects ratings "4.6", counts "(245)",
// times "10:00", years, pincodes and anything with letters.
function looksLikePhone(seg) {
  var s = String(seg).replace(INVISIBLE, '').trim();
  if (!/^\+?[\d\s\-()]+$/.test(s)) return false;
  if (/^\d{1,2}[-/]\d{1,2}[-/]\d{2,4}$/.test(s)) return false;   // a date like 12-05-2024
  var digits = s.replace(/\D/g, '').length;
  return digits >= 8 && digits <= 15;
}

// ASSUMPTION: the current Local Finder has NO tel: links; the phone is plain text in the card
// such as "Open 24 hours · 086574 88772". Split on newlines and the · ⋅ • | separators.
function phoneFromText(text) {
  var segs = String(text == null ? '' : text).replace(INVISIBLE, '').split(/[\n\r·⋅•|]+/);
  for (var i = 0; i < segs.length; i++) {
    if (looksLikePhone(segs[i])) {
      var p = normalizePhone(segs[i]);
      if (p) return p;
    }
  }
  return '';
}

function safeDecode(s) { try { return decodeURIComponent(s); } catch (e) { return s; } }

// SELECTOR: a[href^="tel:"] tried first for robustness (works if Google ever brings it back);
// [data-phone-number] is a speculative extra. The text scan is the path that works today.
var PHONE_LINK_SEL = 'a[href^="tel:"], [data-phone-number]';

function extractPhone(card) {
  var links = card.querySelectorAll(PHONE_LINK_SEL);
  for (var i = 0; i < links.length; i++) {
    var el = links[i];
    var raw = el.getAttribute('data-phone-number') || safeDecode((el.getAttribute('href') || '').replace(/^tel:/i, ''));
    var p = normalizePhone(raw);
    if (p) return p;
  }
  return phoneFromText(card.innerText || card.textContent || '');
}

// -------------------------------------------------------------- name logic
// SELECTOR: business names live in role="heading" (aria attributes are far more stable than
// Google's auto-generated class names).
var HEADING_SEL = '[role="heading"]';
// SELECTOR (fallback only): semi-stable class names for the name element. UNVERIFIED - these
// are used only when no role="heading" card yields a business.
var NAME_FALLBACK_SEL = '.dbg0pd, .OSrXXb';

function extractName(card) {
  var el = (card.matches && card.matches(HEADING_SEL)) ? card : card.querySelector(HEADING_SEL);
  if (!el) el = card.querySelector(NAME_FALLBACK_SEL);
  if (!el) return '';
  var raw = el.innerText || el.textContent || el.getAttribute('aria-label') || '';
  var lines = String(raw).replace(INVISIBLE, '').split(/\n+/);
  for (var i = 0; i < lines.length; i++) {
    var t = lines[i].replace(/\s+/g, ' ').trim();
    if (t) return t.slice(0, 200);
  }
  return '';
}

// ASSUMPTION: Google also renders NON-business UI as role="heading" (a "Choose what you're
// giving feedback on" menu, a "Customised date range" picker): ~22 headings for ~20 real
// businesses. A real business card has at least one of: a middot separator, a rating like
// "4.6(245)", or a phone number.
// SELECTOR: rating text pattern "4.6(245)" - allows whitespace/newline between the parts.
var RATING_RE = /\b[0-5][.,]\d\s*\(\s*[\d.,]+\s*[KkMm]?\s*\)/;

function hasBusinessSignal(text, phone) {
  if (phone) return true;
  var t = String(text || '');
  return /[·⋅]/.test(t) || RATING_RE.test(t);
}

// ------------------------------------------------------------- website link
// Only used when the user opted in to "Find emails". We just READ the link's address here; the
// background worker (not this page) does any fetching.
// ASSUMPTION: the card has a "Website" button/link whose aria-label or text says "Website",
// possibly wrapped as google.com/url?q=<real url>. Falls back to the first external link.
// SELECTOR: a[href] inside the card.
var GOOGLE_HOST_RE = /(^|\.)(google|gstatic|googleusercontent|ggpht|goo\.gl|youtube)\./i;
// Social / aggregator pages never hold the business's own contact email.
var NO_EMAIL_HOST_RE = /(^|\.)(facebook|instagram|twitter|x|linkedin|pinterest|wa|whatsapp|t|justdial|sulekha|tripadvisor|yelp|zomato|swiggy|practo|lybrate)\.(com|me|in|co\.in|net|org)$/i;

function unwrapGoogleUrl(href) {
  try {
    var u = new URL(href, location.href);
    if (GOOGLE_HOST_RE.test(u.hostname) && u.pathname === '/url') return u.searchParams.get('q') || u.searchParams.get('url') || '';
    return u.href;
  } catch (e) { return ''; }
}

function extractWebsite(card) {
  var links = card.querySelectorAll('a[href]');
  var fallback = '';
  for (var i = 0; i < links.length; i++) {
    var a = links[i];
    var href = unwrapGoogleUrl(a.getAttribute('href') || '');
    if (!/^https?:\/\//i.test(href)) continue;
    var host = '';
    try { host = new URL(href).hostname; } catch (e) { continue; }
    if (GOOGLE_HOST_RE.test(host) || NO_EMAIL_HOST_RE.test(host)) continue;
    var label = (a.getAttribute('aria-label') || a.innerText || a.textContent || '').trim();
    if (/website/i.test(label)) return href.slice(0, 500);
    if (!fallback) fallback = href.slice(0, 500);
  }
  return fallback;
}

// ----------------------------------------------------------- card discovery
// SELECTOR: containers we never climb out of when looking for a card.
var STOP_ANCESTORS = '#rso, #search, #center_col, #main, #rcnt, [role="main"]';
var MAX_CLIMB = 8;
var MAX_CARD_TEXT = 1200;   // ASSUMPTION: one card's text is short; a bigger node is the whole list

// SELECTOR (primary): start from every role="heading" and climb to the HIGHEST ancestor that
// still contains exactly one heading. That ancestor is that business's card, including the
// phone line, without depending on any class name.
function discoverCardsByHeading() {
  var headings = Array.prototype.slice.call(document.querySelectorAll(HEADING_SEL));
  var cards = [];
  var used = new Set();
  headings.forEach(function (h) {
    try {
      var card = h;
      var p = h.parentElement;
      for (var i = 0; p && i < MAX_CLIMB; i++) {
        if (p === document.body || p === document.documentElement) break;
        if (p.matches(STOP_ANCESTORS)) break;
        var count = 0;
        for (var j = 0; j < headings.length; j++) if (p.contains(headings[j])) count++;
        if (count > 1) break;
        if ((p.innerText || '').length > MAX_CARD_TEXT) break;
        card = p;
        p = p.parentElement;
      }
      if (!used.has(card)) { used.add(card); cards.push(card); }
    } catch (e) { console.debug(LOG, 'heading skipped', e); }
  });
  return cards;
}

// SELECTOR (fallback): Google's semi-stable class names / data attributes for a listing card.
// UNVERIFIED and may rot - only used when the heading-based discovery finds no business.
var CARD_FALLBACK_SEL = '.VkpGBb, .uMdZh, div[data-cid], .rllt__details';

function discoverCardsByClass() {
  return Array.prototype.slice.call(document.querySelectorAll(CARD_FALLBACK_SEL));
}

function discoverCards() { return discoverCardsByHeading(); }

// ----------------------------------------------------- Google's own place data
// ASSUMPTION (verified on the live page, Oct 2026): the visible list cards carry NO phone number, but the
// page ships a data blob in a <script> with one record per place, each field labelled:
//   ["Bombay Dental Centre",h,2,1,[..],"Place name"],["Dental clinic",h,3,..,"Place category"],
//   ["<address>",h,4,..,"Place location"],["Open · Closes 9 pm",h,5,..,"Place opening hours"],
//   ["089895 38512",h,6,..,"Place phone number"],["https://site/",h,7,..,"Place website"]
// A place with no phone simply has no "Place phone number" entry. Labels are English, which is why the
// finder URL is requested with hl=en. This is the best source for phone + website; the card-text scan below
// stays as a fallback in case Google renames the labels.
function jsonStr(s) { try { return JSON.parse('"' + s + '"'); } catch (e) { return s; } }

// ASSUMPTION (verified live, Oct 2026): just before a place's labelled records, the same blob holds
//   ["Name",[4.7,null,null,[888]], ...  "0x3bc2bf881e459a07:0xafc040a99b72f7c5" ... "ChIJ..." ... 18.515844,73.841866 ...
// = rating + review count, Google's feature id (the second half is the "cid" used by google.com/maps?cid=), place id and
// coordinates. They are read from the stretch between the name and its "Place name" label; any that isn't there stays blank.
function readPlaceMeta(t, labelIndex, rawName, rec) {
  try {
    var needle = '["' + rawName + '",[';
    var start = t.lastIndexOf(needle, labelIndex);
    if (start < 0 || labelIndex - start > 6000) return;
    var block = t.slice(start, labelIndex);
    var r = /^\["(?:[^"\\]|\\.)*",\[(\d(?:\.\d+)?),null,null,\[(\d+)\]\]/.exec(block);
    if (r) { rec.rating = Math.round(parseFloat(r[1]) * 10) / 10; rec.reviews = parseInt(r[2], 10); }
    var c = /"(0x[0-9a-f]+:0x[0-9a-f]+)"/.exec(block);
    if (c) rec.cid = c[1];
    var p = /"(ChIJ[\w-]{10,})"/.exec(block);
    if (p) rec.placeId = p[1];
    // The coordinates sit in the place's header, just BEFORE its name array ("...svid=...",20.000698,73.77764,null,"Chd..."),
    // so take the last pair in the stretch before it.
    var pre = t.slice(Math.max(0, start - 1500), start), llRe = /(-?\d{1,2}\.\d{4,}),(-?\d{2,3}\.\d{4,})/g, ll, last = null;
    while ((ll = llRe.exec(pre))) last = ll;
    if (last) { rec.lat = last[1]; rec.lng = last[2]; }
  } catch (e) { /* the extra fields are optional */ }
}

function readPlaceData() {
  var list = [];
  try {
    var scripts = document.getElementsByTagName('script');
    for (var i = 0; i < scripts.length; i++) {
      var t = scripts[i].textContent;
      if (!t || t.indexOf('Place name') < 0) continue;
      var re = /\["((?:[^"\\]|\\.)*)",-?\d+,\d+,\d+,\[\d+,null,\d+\],"Place (name|category|location|opening hours|phone number|website)"\]/g;
      var rec = null, m;
      while ((m = re.exec(t))) {
        var val = String(jsonStr(m[1])).replace(INVISIBLE, '').replace(/\s+/g, ' ').trim();
        if (m[2] === 'name') { rec = { name: val, used: false }; list.push(rec); readPlaceMeta(t, m.index, m[1], rec); }
        else if (rec) {
          if (m[2] === 'phone number') rec.phone = val;
          else if (m[2] === 'website') rec.website = val;
          else if (m[2] === 'location') rec.location = val;
          else if (m[2] === 'category') rec.category = val;
          else if (m[2] === 'opening hours') rec.hours = val;
        }
      }
    }
  } catch (e) { console.debug(LOG, 'place data unreadable', e); }
  return list;
}

// Match a card to its record by name; same-name branches are told apart by address.
function matchPlace(places, name, cardText) {
  var key = name.toLowerCase(), cands = places.filter(function (p) { return !p.used && p.name.toLowerCase() === key; });
  if (!cands.length) return null;
  var pick = cands[0];
  if (cands.length > 1) {
    var low = String(cardText).toLowerCase();
    for (var i = 0; i < cands.length; i++) {
      var loc = (cands[i].location || '').toLowerCase().slice(0, 25);
      if (loc && low.indexOf(loc) >= 0) { pick = cands[i]; break; }
    }
  }
  pick.used = true;
  return pick;
}

// Every business on the page becomes a lead, with or without a phone: the app decides what is a real mobile
// and writes "Not found" for the rest.
function evaluate(cards) {
  var leads = [], names = [], businessCount = 0, noPhone = 0;
  var places = readPlaceData();
  cards.forEach(function (card) {
    try {                                          // fail soft: a bad card never kills the run
      var name = extractName(card);
      if (!name) return;
      var text = card.innerText || card.textContent || '';
      var place = matchPlace(places, name, text);
      var phone = (place && place.phone) ? place.phone : extractPhone(card);
      if (!hasBusinessSignal(text, phone) && !place) return; // non-business heading (menu, date picker...)
      businessCount++;
      names.push(name);
      if (!phone) noPhone++;
      var lead = { name: name, phone: phone || '' };
      var site = (place && place.website) ? place.website : extractWebsite(card);
      if (site) lead.website = site;
      if (place && place.location) lead.location = place.location;
      if (place) {                                  // extra fields for the column chooser (all optional)
        if (place.category) lead.category = place.category;
        if (place.hours) lead.hours = place.hours;
        if (place.rating != null) { lead.rating = place.rating; lead.reviews = place.reviews; }
        if (place.cid) lead.cid = place.cid;
        if (place.lat) { lead.lat = place.lat; lead.lng = place.lng; }
      }
      leads.push(lead);
    } catch (e) { console.debug(LOG, 'card skipped', e); }
  });
  return { leads: leads, businessCount: businessCount, noPhone: noPhone, signature: names.slice(0, 5).join('|') };
}

function scan() {
  var res;
  try { res = evaluate(discoverCards()); } catch (e) { console.debug(LOG, 'discovery failed', e); }
  if (!res || res.businessCount === 0) {
    try { var fb = evaluate(discoverCardsByClass()); if (fb.businessCount > 0) res = fb; } catch (e) { /* ignore */ }
  }
  return res || { leads: [], businessCount: 0, noPhone: 0, signature: '' };
}

// ---------------------------------------------------------------- pagination
// SELECTOR: the Next control. #pnnext is the classic id; aria-labels are the backups.
var NEXT_SELECTORS = ['#pnnext', 'a[aria-label="Next page"]', 'a[aria-label="Next"]'];

function hasNextPage() {
  for (var i = 0; i < NEXT_SELECTORS.length; i++) {
    var el = document.querySelector(NEXT_SELECTORS[i]);
    if (el && el.getAttribute('aria-disabled') !== 'true') return true;
  }
  return false;
}

// ------------------------------------------------------------------- CAPTCHA
// SELECTOR: CAPTCHA / block widgets. We only DETECT; we never try to solve or bypass.
var CAPTCHA_SELECTORS = ['#captcha-form', 'iframe[src*="recaptcha"]', '.g-recaptcha', 'form[action*="/sorry/"]'];
// ASSUMPTION: Google's block page says "unusual traffic". Text is only trusted when the page
// has no businesses, so a review mentioning those words can't cause a false alarm.
var CAPTCHA_TEXT_RE = /unusual traffic|not a robot|automated queries/i;

function detectCaptcha(businessCount) {
  if (location.pathname.indexOf('/sorry') === 0) return true;
  for (var i = 0; i < CAPTCHA_SELECTORS.length; i++) {
    if (document.querySelector(CAPTCHA_SELECTORS[i])) return true;
  }
  if (!businessCount) {
    var text = (document.body && document.body.innerText) || '';
    if (CAPTCHA_TEXT_RE.test(text)) return true;
  }
  return false;
}

// ---------------------------------------------------------------------- main
async function scanWithPatience() {
  await sleep(700);                                   // let late rendering settle
  var res = scan();
  var deadline = Date.now() + 4000;
  while (res.businessCount === 0 && Date.now() < deadline) {
    if (detectCaptcha(0)) return res;                 // no point waiting on a block page
    await sleep(300);
    res = scan();
  }
  if (res.businessCount > 0) {
    await sleep(500);                                 // cards arrive in bursts; re-scan once settled
    res = scan();
  } else {
    await sleep(1500);                                // first pass found nothing: retry once
    res = scan();
  }
  return res;
}


  var res = await scanWithPatience();
  return {
    leads: res.leads, businessCount: res.businessCount, noPhone: res.noPhone, signature: res.signature,
    hasNext: hasNextPage(), captcha: detectCaptcha(res.businessCount), url: location.href
  };
})()
