// GENERATED by tools/sync-from-extension.js from ScrapeMASTER/background.js - do not edit by hand.
'use strict';
const EMAIL_CONCURRENCY = 6;
const FETCH_TIMEOUT_MS = 10000;
const MAX_FETCHES_PER_SITE = 12;
const SITE_BUDGET_MS = 40000;
const MAX_HTML_CHARS = 1500000;
const EMAIL_RE_FULL = /^[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,24}$/;
// Bounded quantifiers: an unbounded local part makes this regex quadratic on long base64/minified runs and freezes the app.
const EMAIL_RE_G = /[A-Za-z0-9._%+-]{1,64}@[A-Za-z0-9-]{1,63}(?:\.[A-Za-z0-9-]{1,63}){0,6}\.[A-Za-z]{2,24}/g;
const CONTACT_PATHS = [
  '/contact', '/contact-us', '/contactus', '/contact.html', '/contact-us.html', '/contactus.html',
  '/contact.php', '/contactus.php', '/contact-us.php', '/about', '/about-us', '/aboutus',
  '/about.html', '/about-us.html', '/reach-us', '/get-in-touch', '/enquiry', '/support'
];
// Third-party / placeholder addresses that are never the business's own.
const JUNK_DOMAINS = /(^|\.)(example\.com|domain\.com|yourdomain\.com|yoursite\.com|email\.com|test\.com|sentry\.io|sentry-next\.wixpress\.com|wixpress\.com|wix\.com|squarespace\.com|godaddy\.com|wordpress\.com|wordpress\.org|shopify\.com|google\.com|googlemail\.com|schema\.org|w3\.org|gravatar\.com|facebook\.com|twitter\.com|instagram\.com|cloudflare\.com|jquery\.com|bootstrapcdn\.com)$/i;
const JUNK_LOCAL = /^(your|yourname|your\.?email|name|fullname|firstname|lastname|first\.?last|email|user|username|example|sample|demo|test|testing|you|someone|abc|xyz|john\.?doe|john\.?smith|jane\.?doe|jane\.?smith|johnsmith|janedoe|noreply|no-reply|donotreply|do-not-reply|mailer-daemon|postmaster|webmaster)$/i;
// Form placeholders ("e.g. johnsmith@gmail.com") are not the business's address; drop them before scanning.
// Matches both the HTML attribute (placeholder="...") and the JSON form ("placeholder":"...").
const PLACEHOLDER_RE = /["']?placeholder["']?\s*[:=]\s*(?:"[^"]*"|'[^']*')|\b(?:e\.g\.?|eg:|for example|example:)\s*[\w.+-]+@[\w.-]+/gi;
const ASSET_TLD = /\.(png|jpe?g|gif|svg|webp|css|js|woff2?|ttf|ico|avif|map|json|php|html?)$/i;
const FREE_MAIL = /(^|\.)(gmail|yahoo|ymail|outlook|hotmail|rediffmail|live|icloud|proton|protonmail)\./i;
const ROLE_LOCAL = /^(info|contact|sales|enquiry|enquiries|inquiry|hello|support|care|office|admin|mail|reception|booking|appointments?|query|customercare|help)$/i;
const FILE_EXT = /\.(pdf|jpe?g|png|gif|svg|webp|zip|docx?|xlsx?|mp4|mp3|css|js)(\?|$)/i;



// Only plain public http(s) sites: no IP literals, no localhost/intranet names (the URLs come
// from web pages, so never let them point the worker at the user's own network).
function safeSiteUrl(raw) {
  try {
    const u = new URL(String(raw || ''));
    if (u.protocol !== 'http:' && u.protocol !== 'https:') return null;
    const h = u.hostname.toLowerCase();
    if (!h || h === 'localhost' || h.indexOf('.') < 0) return null;
    if (/^[\d.]+$/.test(h) || h.indexOf(':') >= 0 || h.charAt(0) === '[') return null;
    if (/\.(local|localhost|internal|lan|home|corp)$/.test(h)) return null;
    return u;
  } catch (e) { return null; }
}

async function fetchText(url, parent) {
  const ctl = new AbortController();
  const timeout = setTimeout(() => ctl.abort(), FETCH_TIMEOUT_MS);
  const onAbort = () => ctl.abort();
  parent.addEventListener('abort', onAbort);
  try {
    const r = await fetch(url, { signal: ctl.signal, credentials: 'omit', redirect: 'follow' });
    if (!r.ok || !safeSiteUrl(r.url)) return null;      // also re-check where redirects ended up
    const type = r.headers.get('content-type') || '';
    if (type && !/text|html|xml|json/i.test(type)) return null;
    return (await r.text()).slice(0, MAX_HTML_CHARS);
  } catch (e) { return null; }
  finally { clearTimeout(timeout); parent.removeEventListener('abort', onAbort); }
}

function decodeHex(hex, skip) {                            // Cloudflare "email protection" (key byte first)
  try {
    const key = parseInt(hex.slice(0, 2), 16);
    let out = '';
    for (let i = 2; i < hex.length; i += 2) out += String.fromCharCode(parseInt(hex.slice(i, i + 2), 16) ^ key);
    return out;
  } catch (e) { return ''; }
}

function chr(code) {
  try { return code > 0 && code < 0x110000 ? String.fromCodePoint(code) : ''; } catch (e) { return ''; }
}

// Pages often embed huge base64 images / minified blobs. They can't contain an address, and long unbroken runs are what
// make regexes crawl, so cut them out before anything is scanned.
function stripBlobs(html) {
  return String(html).replace(/data:[\w/+.-]+;base64,[A-Za-z0-9+/=]*/gi, ' ').replace(/[A-Za-z0-9+/=_%-]{150,}/g, ' ');
}

// Undo the usual ways sites hide an address from naive scrapers.
function deobfuscate(s) {
  return String(s)
    .replace(/&#x([0-9a-f]+);?/gi, (m, h) => chr(parseInt(h, 16)))
    .replace(/&#(\d+);?/g, (m, d) => chr(parseInt(d, 10)))
    .replace(/&commat;/gi, '@').replace(/&period;/gi, '.').replace(/&amp;/gi, '&')
    .replace(/\\u0040|\\x40/gi, '@').replace(/\\u002e|\\x2e/gi, '.')
    .replace(/%40/g, '@')
    .replace(/\s*[\[({<]\s*(?:at|@)\s*[\])}>]\s*/gi, '@')
    .replace(/\s*[\[({<]\s*(?:dot|\.)\s*[\])}>]\s*/gi, '.');
}

function acceptEmail(e) {
  e = String(e || '').trim().replace(/^[.\-_]+|[.\-_]+$/g, '').toLowerCase();
  if (e.length > 80 || !EMAIL_RE_FULL.test(e)) return '';
  const at = e.lastIndexOf('@');
  const local = e.slice(0, at), domain = e.slice(at + 1);
  if (ASSET_TLD.test(domain) || JUNK_DOMAINS.test(domain) || JUNK_LOCAL.test(local)) return '';
  if (/^\d+x?$/.test(local)) return '';
  return e;
}

// Returns [{email, mailto}] in page order.
function extractEmails(rawHtml) {
  const out = [];
  const push = (raw, mailto) => { const e = acceptEmail(raw); if (e) out.push({ email: e, mailto }); };
  const html = deobfuscate(stripBlobs(rawHtml)).replace(PLACEHOLDER_RE, ' ');
  let m;
  const cf = /data-cfemail=["']([0-9a-fA-F]+)["']/g;
  while ((m = cf.exec(html))) push(decodeHex(m[1]), true);
  const cf2 = /email-protection#([0-9a-fA-F]{6,})/g;
  while ((m = cf2.exec(html))) push(decodeHex(m[1]), true);
  const mt = /mailto:([^"'<>\s?]+)/gi;
  while ((m = mt.exec(html))) {
    let v = m[1];
    try { v = decodeURIComponent(v); } catch (e) { /* keep raw */ }
    v.split(/[,;]/).forEach(x => push(x, true));
  }
  // Plain text, twice: as-is, and with inline tags removed so "info<span>@</span>shop.com" joins up.
  const joined = html.replace(/<\/?(?:span|b|i|u|em|strong|font|small|wbr)\b[^>]*>/gi, '').replace(/<[^>]+>/g, ' ');
  [html, joined].forEach(t => (t.match(EMAIL_RE_G) || []).forEach(f => push(f, false)));
  return out;
}

function baseHost(h) { return String(h).toLowerCase().replace(/^www\./, ''); }

function siteMatches(email, host) {
  const a = baseHost(email.slice(email.lastIndexOf('@') + 1)), b = baseHost(host);
  return a === b || b.endsWith('.' + a) || a.endsWith('.' + b);
}

function scoreEmail(c, host) {
  let s = 0;
  if (siteMatches(c.email, host)) s += 4;
  else if (FREE_MAIL.test(c.email.slice(c.email.lastIndexOf('@') + 1))) s += 2;
  if (c.mailto) s += 1;
  if (ROLE_LOCAL.test(c.email.slice(0, c.email.lastIndexOf('@')))) s += 0.5;
  return s;
}

// Links on the page that probably lead to a contact/about page of the SAME site, best first.
function contactLinks(html, base) {
  const found = new Map();
  const re = /<a\b[^>]*?href=["']([^"'#]+)["'][^>]*>([\s\S]{0,160}?)<\/a>/gi;
  let m;
  while ((m = re.exec(html))) {
    try {
      const u = new URL(m[1], base);
      if ((u.protocol !== 'http:' && u.protocol !== 'https:') || baseHost(u.hostname) !== baseHost(new URL(base).hostname)) continue;
      if (FILE_EXT.test(u.pathname) || !safeSiteUrl(u.href)) continue;
      const hay = (u.pathname + ' ' + m[2].replace(/<[^>]+>/g, ' ')).toLowerCase();
      let score = 0;
      if (/contact|reach.?us|get.?in.?touch|enquir|inquir/.test(hay)) score = 3;
      else if (/about/.test(hay)) score = 2;
      else if (/support|location|find.?us|connect|write.?to|visit.?us/.test(hay)) score = 1;
      if (score && (!found.has(u.href) || found.get(u.href) < score)) found.set(u.href, score);
    } catch (e) { /* bad href */ }
  }
  return Array.from(found.entries()).sort((a, b) => b[1] - a[1]).map(x => x[0]).slice(0, 6);
}

function siteVariants(u) {
  const list = [u.href];
  const alt = new URL(u.href);
  alt.hostname = u.hostname.startsWith('www.') ? u.hostname.slice(4) : 'www.' + u.hostname;
  list.push(alt.href);
  if (u.protocol === 'https:') { const h = new URL(u.href); h.protocol = 'http:'; list.push(h.href); }
  return list;
}

// A real MOBILE number, normalised to +<country code><number> with no spaces. Supported:
//   India  10 digits starting 6-9, written with or without +91 / 91 / 0 in front     -> +91XXXXXXXXXX
//   UAE    9 digits starting 5 (50 52 54 55 56 58), with or without +971 / 00971 / 0   -> +9715XXXXXXXX
// Landlines (STD codes like 022..., UAE 04...) are NOT mobiles. Anything else is rejected, so it reads "Not found".
function mobileOf(raw) {
  let d = String(raw == null ? '' : raw).replace(/[​-‏‪-‮⁠⁦-⁩﻿]/g, '').replace(/\D/g, '');
  if (d.startsWith('00')) d = d.slice(2);                                       // 00971... / 0091...
  // UAE
  let u = d;
  if (u.length === 12 && u.startsWith('971')) u = u.slice(3);
  else if (u.length === 10 && u.startsWith('05')) u = u.slice(1);
  if (/^5[024568]\d{7}$/.test(u) && (d.length === 12 || d.length === 10 || d.length === 9)) return { ten: u, out: '+971' + u };
  // India
  let i = d;
  if (i.length === 13 && i.startsWith('091')) i = i.slice(3);
  else if (i.length === 12 && i.startsWith('91')) i = i.slice(2);
  else if (i.length === 11 && i.startsWith('0')) i = i.slice(1);
  return /^[6-9]\d{9}$/.test(i) ? { ten: i, out: '+91' + i } : null;
}

// Any usable phone number, written without spaces: "+<country code><number>". Mobiles (see mobileOf) are typed 'mobile',
// every other valid number 'landline'. `region` ('IN' | 'AE' | '') tells how to read a local number that starts with 0:
// 022 2639 5533 -> +912226395533 (IN), 04 335 4041 -> +97143354041 (AE). With no region a local number stays as written.
function phoneOf(raw, region) {
  const s = String(raw == null ? '' : raw).replace(/[​-‏‪-‮⁠⁦-⁩﻿]/g, '').trim();
  if (!s) return null;
  const mob = mobileOf(s);
  if (mob) return { out: mob.out, type: 'mobile' };
  let d = s.replace(/\D/g, ''), intl = s.charAt(0) === '+';
  if (d.startsWith('00')) { d = d.slice(2); intl = true; }
  if (d.length < 8 || d.length > 15 || /^(\d)\1+$/.test(d)) return null;
  if (!intl) {
    if (d.startsWith('971') && d.length >= 11 && d.length <= 12) intl = true;
    else if (d.startsWith('91') && d.length === 12) intl = true;
    else if (d.startsWith('0') && region === 'AE' && d.length >= 9 && d.length <= 10) { d = '971' + d.slice(1); intl = true; }
    else if (d.startsWith('0') && region === 'IN' && d.length >= 10 && d.length <= 12) { d = '91' + d.slice(1); intl = true; }
    else if (d.startsWith('800') && region === 'AE') { d = '971' + d; intl = true; }          // UAE toll-free
    else if (d.startsWith('1800') && region === 'IN') { d = '91' + d; intl = true; }          // India toll-free
  }
  return { out: (intl ? '+' : '') + d, type: 'landline' };
}


// ---- address -> city / state / pincode, and a clean website link ----
const INDIAN_STATES = [
  'Andaman and Nicobar Islands', 'Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
  'Chandigarh', 'Chhattisgarh', 'Chattisgarh', 'Dadra and Nagar Haveli', 'Dadra & Nagar Haveli', 'Daman and Diu', 'Daman & Diu',
  'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'NCT of Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
  'Jammu and Kashmir', 'Jammu & Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh',
  'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Orissa', 'Puducherry', 'Pondicherry', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'Uttaranchal', 'West Bengal'
];
const PIN_RE = /(?<!\d)[1-9]\d{2}\s?\d{3}(?!\d)/;

const UAE_EMIRATES = ['Abu Dhabi', 'Dubai', 'Sharjah', 'Ajman', 'Umm Al Quwain', 'Ras Al Khaimah', 'Fujairah'];
const UAE_COUNTRY_RE = /(^|[\s,-])(united arab emirates|uae|u\.a\.e\.?)\s*$/i;

// Google's address looks like "1st floor, Hubtown Premiere, Four Bungalows, Andheri West, Mumbai, Maharashtra 400053" (India)
// or "Oxford Towers - 805 - Business Bay - Dubai - United Arab Emirates" (UAE).
// City = the part just before "State pincode"; pincode = the last 6-digit PIN. Anything not found stays ''.
function parseAddress(loc) {
  const s = String(loc == null ? '' : loc).replace(/\s+/g, ' ').trim();
  const out = { city: '', state: '', pincode: '', country: '' };
  if (!s) return out;
  if (UAE_COUNTRY_RE.test(s)) {
    out.country = 'United Arab Emirates';
    const parts = s.replace(UAE_COUNTRY_RE, '').replace(/[\s,-]+$/, '').split(/\s+-\s+|,/).map(x => x.trim()).filter(Boolean);
    const em = parts.slice().reverse().find(p => UAE_EMIRATES.some(e => e.toLowerCase() === p.toLowerCase()));
    if (em) { out.state = UAE_EMIRATES.find(e => e.toLowerCase() === em.toLowerCase()); out.city = out.state; }
    else if (parts.length) out.city = parts[parts.length - 1].slice(0, 80);
    return out;
  }
  const pins = s.match(new RegExp(PIN_RE.source, 'g'));
  if (pins) out.pincode = pins[pins.length - 1].replace(/\s/g, '');
  const parts = s.split(',').map(x => x.trim()).filter(Boolean);
  if (parts.length && /^india$/i.test(parts[parts.length - 1])) { parts.pop(); out.country = 'India'; }
  const tail = parts.length ? parts[parts.length - 1] : '';
  const rest = tail.replace(PIN_RE, '').trim();
  const state = INDIAN_STATES.find(x => x.toLowerCase() === rest.toLowerCase());
  if (state) {
    out.state = state;
    out.country = 'India';
    out.city = parts.length > 1 ? parts[parts.length - 2] : '';
  } else if (rest && out.pincode) {
    out.city = rest;                                   // "Mumbai 400053"
  }
  out.city = out.city.replace(PIN_RE, '').replace(/\s+/g, ' ').trim().slice(0, 80);
  return out;
}

// The website Google lists carries tracking parameters (?utm_source=gmb...). Keep the address, drop the tracking.
function cleanSiteUrl(u) {
  try {
    const c = new URL(u.href);
    Array.from(c.searchParams.keys()).forEach(k => { if (/^(utm_|gclid|fbclid|gbraid|wbraid|msclkid|ved$|sa$)/i.test(k)) c.searchParams.delete(k); });
    c.hash = '';
    return c.href.slice(0, 500);
  } catch (e) { return u.href.slice(0, 500); }
}

// Phone numbers on a web page: [{out, type, strong}]. Strong evidence first: WhatsApp links (wa.me/...) and tel: links.
// Then numbers in the visible text: a MOBILE is accepted anywhere; any other number (landline) only when it carries a country
// code (+91 / +971) or sits right after a word like Tel / Phone / Call / Office, so random digit strings aren't mistaken for phones.
function extractPhones(rawHtml, region) {
  const html = deobfuscate(stripBlobs(rawHtml));
  const out = [];
  const add = (raw, strong) => { const p = phoneOf(raw, region); if (p) out.push({ out: p.out, type: p.type, strong }); };
  let m;
  const wa = /(?:wa\.me\/|whatsapp\.com\/send\/?\?(?:[^"'\s>]*&)?phone=|whatsapp:\/\/send\?(?:[^"'\s>]*&)?phone=)\+?(\d{10,13})/gi;
  while ((m = wa.exec(html))) add(m[1], true);
  const tel = /href=["']tel:([^"']+)["']/gi;
  while ((m = tel.exec(html))) { let v = m[1]; try { v = decodeURIComponent(v); } catch (e) { /* keep raw */ } add(v, true); }
  const text = html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, ' ').replace(/<[^>]+>/g, ' ');
  const re = /\+?\d[\d\s().-]{8,17}\d/g;
  while ((m = re.exec(text))) {
    const raw = m[0];
    if (mobileOf(raw)) { add(raw, false); continue; }
    const before = text.slice(Math.max(0, m.index - 28), m.index);
    if (raw.charAt(0) === '+' || /(tel|phone|call|ph|mob|mobile|contact|landline|office|whatsapp|helpline|reception|fax)(\s+(us|now|on|at|no|number|nos?\.?|for appointments?|to book))?\W{0,16}$/i.test(before)) add(raw, false);
  }
  return out;
}

// Mobiles only (kept for callers that just want those): [{ten, out, strong}]
function extractMobiles(rawHtml) {
  return extractPhones(rawHtml, '').filter(p => p.type === 'mobile').map(p => ({ ten: p.out.replace(/^\+(91|971)/, ''), out: p.out, strong: p.strong }));
}

// Social profile links on the business's own site: the first one found per network. Share / login / tracking links
// and bare home pages (facebook.com/) are skipped.
function extractSocials(rawHtml) {
  const html = stripBlobs(rawHtml);
  const out = {};
  const re = /href=["'](https?:\/\/(?:[a-z0-9-]+\.)?(facebook|instagram|linkedin|twitter|x)\.com\/[^"'\s<>]{2,160})["']/gi;
  let m;
  while ((m = re.exec(html))) {
    const net = m[2].toLowerCase() === 'x' ? 'twitter' : m[2].toLowerCase();
    if (out[net]) continue;
    const url = m[1];
    if (/sharer|share\.php|\/share|intent\/|dialog\/|plugins\/|login|\/tr\?|hashtag|explore\/|policy|privacy|\/legal|\/p\/|\/reel/i.test(url)) continue;
    const path = url.replace(/^https?:\/\/[^/]+/, '').split(/[?#]/)[0].replace(/\/+$/, '');
    if (path.length < 2) continue;
    out[net] = url.split(/[?#]/)[0].slice(0, 200);
  }
  return out;
}

// Looks for the business's public email and phone numbers on its own website.
// Returns {email, mobile, landline, social}; each is '' / {} when nothing was found. Nothing is ever guessed.
// opts.needPhone: also collect phone numbers (mobile preferred, landline as the fallback); opts.region: 'IN' | 'AE' | ''.
async function findContactForSite(site, signal, opts) {
  const needPhone = !!(opts && (opts.needPhone || opts.needMobile));
  const region = (opts && opts.region) || '';
  const empty = { email: '', mobile: '', landline: '', social: {} };
  const u = safeSiteUrl(site);
  if (!u) return empty;
  const started = Date.now();
  const tried = new Set();
  const mobiles = new Map(), landlines = new Map();       // "+<number>" -> evidence score
  const socials = {};                                     // facebook / instagram / linkedin / twitter
  let fetched = 0, best = null, bestScore = -1, host = u.hostname.toLowerCase();
  const budget = () => !signal.aborted && fetched < MAX_FETCHES_PER_SITE && Date.now() - started < SITE_BUDGET_MS;
  const enough = () => bestScore >= 5 && (!needPhone || mobiles.size > 0);
  const top = map => { let r = '', t = -1; map.forEach((score, k) => { if (score > t) { t = score; r = k; } }); return r; };
  const result = () => ({ email: best || '', mobile: top(mobiles), landline: top(landlines), social: socials });
  const consider = html => {
    extractEmails(html).forEach(c => {
      const sc = scoreEmail(c, host);
      if (sc > bestScore) { best = c.email; bestScore = sc; }
    });
    const so = extractSocials(html);
    Object.keys(so).forEach(k => { if (!socials[k]) socials[k] = so[k]; });
    if (needPhone) extractPhones(html, region).forEach(c => {
      const map = c.type === 'mobile' ? mobiles : landlines;
      map.set(c.out, (map.get(c.out) || 0) + (c.strong ? 3 : 1));
    });
  };
  const get = async url => {
    if (tried.has(url) || !budget()) return null;
    tried.add(url);
    fetched++;
    const html = await fetchText(url, signal);
    if (html !== null) consider(html);
    return html;
  };

  // 1) home page (and its www / http variants if it won't load)
  let home = null, base = null;
  for (const v of siteVariants(u)) {
    home = await get(v);
    if (home !== null) { base = v; break; }
    if (!budget()) break;
  }
  if (home === null) return empty;
  host = new URL(base).hostname.toLowerCase();
  if (enough()) return result();

  // 2) contact-looking links from the home page + the most common contact URLs
  const origin = new URL(base).origin;
  const firstPaths = CONTACT_PATHS.slice(0, 4).map(p => origin + p);
  for (const url of contactLinks(home, base).concat(firstPaths)) {
    if (!budget() || enough()) break;
    await get(url);
  }

  // 3) still missing something: look in the sitemap for contact/about pages the home page never links to
  if (!enough() && budget()) {
    const sm = await get(origin + '/sitemap.xml');
    if (sm) {
      const locs = [];
      const re = /<loc>\s*([^<\s]+)\s*<\/loc>/gi;
      let m;
      while ((m = re.exec(sm)) && locs.length < 3) {
        if (/contact|about|reach|enquir|inquir|support/i.test(m[1]) && baseHost((safeSiteUrl(m[1]) || { hostname: '' }).hostname) === baseHost(host)) locs.push(m[1]);
      }
      for (const url of locs) { if (!budget() || enough()) break; await get(url); }
    }
  }

  // 4) still nothing: the rarer contact URLs
  for (const p of CONTACT_PATHS.slice(4)) {
    if (!budget() || (best !== null && (!needPhone || mobiles.size > 0 || landlines.size > 0))) break;
    await get(origin + p);
  }
  return result();
}

async function findEmailForSite(site, signal) {
  return (await findContactForSite(site, signal, { needPhone: false })).email;
}

// Called when the searches are over. Waits for lookups that are still running, then finishes.

module.exports = { findEmailForSite, findContactForSite, extractEmails, extractMobiles, extractPhones, phoneOf, extractSocials, mobileOf, parseAddress, cleanSiteUrl, safeSiteUrl, EMAIL_RE_FULL, EMAIL_CONCURRENCY };
